# include "constantes.h"

const char *NOMBRE_CATEGORIA[] = { "Frutas","Animales","Paises","Objetos" };

const char FRUTAS[10][15] = { "MELON","PAPAYA","SANDIA","MANZANA","PERA","NARANJA","UVA","CEREZA","CIRUELA","KIWI" };
const char ANIMALES[10][15] = { "PERRO","GATO","CABALLO","GALLINA","JIRAFA","MONO","VACA","CONEJO","TORTUGA","LOBO" };
const char PAISES[10][15] = { "PERU","COLOMBIA","ARGENTINA","NICARAGUA","ITALIA","MEXICO","CANADA","VENEZUELA","ECUADOR","BRASIL" };
const char OBJETOS[10][15] = { "MOCHILA","RELOJ","ZAPATILLA","MUEBLE","CUADERNO","SILLA","MESA","CELULAR","PUERTA","AURICULARES" };

const int MAX_INTENTOS = 6;
